kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datagate-pvc
  namespace: cpd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
